package com.app.estore.utility;

public enum ProductCategory {
    ELECTRONICS,
    MOBILE_PHONES_AND_ACCESSORIES,
    COMPUTERS_AND_LAPTOPS,
    HOME_APPLIANCES,
    FASHION,
    MEN,
    WOMEN,
    KIDS,
    FOOTWEAR,
    BEAUTY_AND_PERSONAL_CARE,
    HEALTH_AND_WELLNESS,
    GROCERIES_AND_FOOD,
    HOME_AND_KITCHEN,
    FURNITURE,
    SPORTS_AND_FITNESS,
    BOOKS_AND_STATIONERY,
    TOYS_AND_GAMES,
    BABY_PRODUCTS,
    AUTOMOTIVE,
    JEWELRY_AND_WATCHES,
    BAGS_AND_LUGGAGE,
    OFFICE_SUPPLIES,
    PET_SUPPLIES
}

